---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# PortalHacienda

Un paquete de interface R a la API del Portal de Datos del Ministerio de Hacienda.
Buscar, descarcar y proyectar rápidamente series. Se cargan en formato XTS.

## Instalación

Para instalar ejecutar:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("fmgarciadiaz/PortalHacienda")
```

## Ejemplo

Búsqueda, carga y proyección básica de series del Portal.

```{r example}
# Cargar el paquete
library(PortalHacienda)
# Buscar las series de tipo de cambio
Series_TCN <- Search("tipo de cambio")         
# mostrar las primeras series encontradas
knitr::kable(head(Series_TCN) ,"html") %>% kableExtra::kable_styling(font_size = 7)    
# Ahora bajar serie con GET y extender 12 meses con Forecast (usa modelo auto-detectado  de paquete "forecast")
TCN <- Forecast(Get("174.1_T_DE_CATES_0_0_32" , start_date = 2000), 12)       
# Mostrar resultado
plot(TCN , main = "Tipo de Cambio Nominal ($/USD)")
```
